version: "3"
services:
    oritalYpiretis:
        container_name: orital-ypiretis
        build:
            context: .
            args:
                # **NOTE:** All environment variables below are passed to the underlying
                # `Dockerfile` as arguments for the image build step. These environment
                # variables are baked into the built source code as importable constants.
                #
                # See `vite.config.ts` for the environment variables used this way.
                - ACCOUNT_PROVIDER_DOMAIN=${ACCOUNT_PROVIDER_DOMAIN}
                - ACCOUNT_PROVIDER_NAME=${ACCOUNT_PROVIDER_NAME}
                - APP_NAME=${APP_NAME}
                - APP_URL=${APP_URL}
                - ARTICLES_ATTACHMENTS_MAX_FILE_SIZE=${ARTICLES_ATTACHMENTS_MAX_FILE_SIZE}
                - EVENTS_ATTACHMENTS_MAX_FILE_SIZE=${EVENTS_ATTACHMENTS_MAX_FILE_SIZE}
                - NODE_ENV=${NODE_ENV}
                - SERVER_HOST=0.0.0.0
                - SERVER_PORT=${SERVER_PORT}
                - UPLOADS_MAX_FILE_SIZE=${UPLOADS_MAX_FILE_SIZE}
        environment:
            - ACCOUNT_ADMIN_IDENTIFIERS=${ACCOUNT_ADMIN_IDENTIFIERS}
            - ACCOUNT_PROVIDER_DOMAIN=${ACCOUNT_PROVIDER_DOMAIN}
            - ACCOUNT_PROVIDER_NAME=${ACCOUNT_PROVIDER_NAME}
            - APP_NAME=${APP_NAME}
            - APP_URL=${APP_URL}
            - ARTICLES_ATTACHMENTS_MAX_FILE_SIZE=${ARTICLES_ATTACHMENTS_MAX_FILE_SIZE}
            - CRONJOB_ROOMS_DISCONNECT_CLEANUP=${CRONJOB_ROOMS_DISCONNECT_CLEANUP}
            - CRONJOB_ROOMS_LIFETIME_CLEANUP=${CRONJOB_ROOMS_LIFETIME_CLEANUP}
            - CRONJOB_TOKENS_CLEANUP=${CRONJOB_TOKENS_CLEANUP}
            - DATABASE_FILE_PATH=${DATABASE_FILE_PATH}
            - DISCORD_INVITE_CODE=${DISCORD_INVITE_CODE}
            - DISCOVER_EAST_ORGANIZATION_IDENTIFIER=${DISCOVER_EAST_ORGANIZATION_IDENTIFIER}
            - EVENTS_ATTACHMENTS_MAX_FILE_SIZE=${EVENTS_ATTACHMENTS_MAX_FILE_SIZE}
            - GITHUB_ORGANIZATION_IDENTIFIER=${GITHUB_ORGANIZATION_IDENTIFIER}
            - NODE_ENV=${NODE_ENV}
            - QUEUE_EMAILS_MAX=${QUEUE_EMAILS_MAX}
            - ROOMS_DISCONNECT_TTL=${ROOMS_DISCONNECT_TTL}
            - ROOMS_LIFETIME_TTL=${ROOMS_LIFETIME_TTL}
            - SECRET_KEY=${SECRET_KEY}
            - SECRET_SALT=${SECRET_SALT}
            - SERVER_HOST=0.0.0.0
            - SERVER_LOGGING_LEVEL=${SERVER_LOGGING_LEVEL}
            - SERVER_PORT=${SERVER_PORT}
            - SESSION_EPHEMERAL_TTL=${SESSION_EPHEMERAL_TTL}
            - SESSION_PERSISTENT_TTL=${SESSION_PERSISTENT_TTL}
            - SMTP_EMAIL=${SMTP_EMAIL}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - SMTP_PORT=${SMTP_PORT}
            - TOKEN_CALLBACK_TTL=${TOKEN_CALLBACK_TTL}
            - TOKEN_CONSENT_TTL=${TOKEN_CONSENT_TTL}
            - TOKEN_GRANT_TTL=${TOKEN_GRANT_TTL}
            - UPLOADS_DIRECTORY_PATH=${UPLOADS_DIRECTORY_PATH}
            - UPLOADS_MAX_FILE_SIZE=${UPLOADS_MAX_FILE_SIZE}

    caddyProxy:
        container_name: caddy-proxy
        image: caddy:2.10.0-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - oritalYpiretis
        environment:
            - PROXIED_SERVER_HOST=oritalYpiretis
            - PROXIED_SERVER_PORT=${SERVER_PORT}
