name: Continuous Integration

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    checkYpiretis:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                    - windows-2022
                    - macOS-14

        defaults:
            run:
                working-directory: ./packages/ypiretis

        steps:
            - name: Clone Repository
              uses: actions/checkout@v4

            - name: Configure Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.13

            - name: Install Dependencies
              run: bun run deps:cache

            - name: Check Format
              run: bun run check:format

            - name: Check Linting
              run: bun run check:lint

            - name: Check Types
              run: bun run check:types

    buildYpiretis:
        needs: checkYpiretis

        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                    - windows-2022
                    - macOS-14

        defaults:
            run:
                working-directory: ./packages/ypiretis

        steps:
            - name: Clone Repository
              uses: actions/checkout@v4

            - name: Configure Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.13

            - name: Install Dependencies
              run: bun run deps:cache

            - name: Build Application
              run: bun run app:build
